
#type: args

train:
  epochs: 10
  batch_size: 1
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8
  


diffusion:
  layers: 6
  channels: 128
  nheads: 4
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  is_linear: True

model:
  is_unconditional: 0
  timeemb: 64
  featureemb: 1
  target_strategy: "test"
